default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123
  host: grades-db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: grades
test:
  <<: *default
  database: grades-ms_test
production:
  <<: *default
  database: grades-ms_production
  username: grades-ms
  password: <%= ENV['GRADES-MS_DATABASE_PASSWORD'] %>
